@baseURL = http://localhost:8080
@email = aketchum@pallettn.pkm
@password = TheVeryBest96

POST {{baseURL}}/admin/reset

###

# @name user
POST {{baseURL}}/api/users

{
    "password": "{{password}}",
    "email": "{{email}}"
}

###

# @name login
POST {{baseURL}}/api/login

{
    "password": "{{password}}",
    "email": "{{email}}"
}

###

@token = {{login.response.body.token}}
# @name chirp
POST {{baseURL}}/api/chirps
Authorization: Bearer {{token}}

{
    "body": "I wanna be the very best, like no one ever was"
}